module.exports = {
  GET_ALL_GARS : `GET_ALL_GARS`,
  GET_SINGLE_CAR : `GET_SINGLE_CAR`,
  GET_TOP_CARS : `GET_TOP_CARS`,
  LOGIN : `LOGIN`,
  LOGOUT : `LOGOUT`,
  GET_YOUR_CART : `GET_YOUR_CART`,
  SINGLE_USER_INFO : `SINGLE_USER_INFO`,
  GET_ALL_USERS : `GET_ALL_USERS`,
  GET_TOP_USERS : `GET_TOP_USERS`,
  GET_TOP_CARS_ADMIN : `GET_TOP_CARS_ADMIN`,
  GET_LAST_ORDERS : `GET_LAST_ORDERS`
};