module.exports = {
    GET_ALL_GARS : 'GET_ALL_GARS',
    GET_SINGLE_CAR : 'GET_SINGLE_CAR',
    GET_TOP_CARS : 'GET_TOP_CARS',
    LOGIN : 'LOGIN',
    LOGOUT : 'LOGOUT',
    GET_YOUR_CART : 'GET_YOUR_CART'
};